language: node_js

sudo: false

node_js:
  - '7'
  - '6' # LTS
  - '4' # LTS

cache:
  directories:
  - node_modules

env:
  # node 4 likes the G++ v4.8 compiler
  - CXX=g++-4.8

# node 4 likes the G++ v4.8 compiler
# see https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  # Disable the spinner, it looks bad on Travis
  - npm config set spin false
  # Install npm dependencies
  - npm install

script:
  - npm run prepublish
